---
- name: Deploy Dockerized Web Application
  hosts: localhost
  become: yes  

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: web_app_image 
        source: pull
      tags:
        - deployment

    - name: Run Docker Container
      docker_container:
        name: web_app_container
        image: web_app_image 
        state: started
        ports:
          - "8080:5000"
      tags:
        - deployment
