name: app_python

on:
  push:
    paths:
      - "app_python/**"
      - ".github/workflows/app_python-CI.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app_python/**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r app_python/requirements.txt

      - name: Formatting Code
        run: pre-commit run --all-files
        continue-on-error: true

      - name: Lint Code
        run: pre-commit run --all-files

      - name: Run Tests
        run: python app_python/test_app.py
